#ifndef GLOBALINTERFACE_GLOBAL_H
#define GLOBALINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLOBALINTERFACE_LIBRARY)
#  define GLOBALINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define GLOBALINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // GLOBALINTERFACE_GLOBAL_H
